### ISSUE TITLE
User Journey : Volunteers 

### ISSUE THREAD

**Issue by sajedazoabi** [facn2/Something-Good#1]
As a volunteer, I want to go to the App and Get information and create volunteering events:

- [ ] I want to see the App logo and description on the home page. #2 

- [ ] I want to see the events list on the events page when I click the logo on the home page. #3 

- [ ] I want to click an event and see more information and details about the event: Name, description, location, number of participants and date. #4 

- [ ] I want to click a button to indicate my intention of participating in the event. #5 
  
- [ ] I want to be able to create an event. #6
